sonar.projectKey=hotstar-clone
sonar.projectName=hotstar-clone
sonar.projectVersion=1.0
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.host.url=http://192.168.0.105:9000
sonar.login=squ_3376717695dbfc292dcc69ede9aed97618cfb011
